### ISSUE TITLE
Can not start npm

### ISSUE THREAD

**Issue by nthphuong** [Alfresco/generator-alfresco-adf-app#241]
Dear all,

When I run the command : npm start. I get the issue like below:

> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! adf-cli-acs-aps-template@3.6.0 start: `npm run validate-config && ng serve --open`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the adf-cli-acs-aps-template@3.6.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Can you help me? Thanks.

**Comment by eromano** [comment]
Can you give us more details on the step to reproduce it?

**Comment by nthphuong** [comment]
Yes, Eromano.

I run on server: 

> NAME="Ubuntu"
> VERSION="18.04.3 LTS (Bionic Beaver)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 18.04.3 LTS"
> VERSION_ID="18.04"

**STEP:**

1. Install **node**.
node -v

> v11.15.0 

2. Install **yo**.
yo --version

> 3.1.1

3. Install generator-alfresco-adf-app at latest version:
npm install -g generator-alfresco-adf-app@latest

4. vi proxy.conf.js (Update domain of ACS)

5. Install **ng**
- Update "@angular-devkit/build-angular": "^0.802.1" to "@angular-devkit/build-angular": "^0.13.9"
ng --version
![image](https://user-images.githubusercontent.com/8097043/72578756-91b0e680-3909-11ea-85ef-24db17812754.png)

6. Run **npm start** and got the error as below:
![image](https://user-images.githubusercontent.com/8097043/72578807-c91f9300-3909-11ea-9779-40373f73b550.png)

Can you give me the solution to resolve it?

Thank you so much!

**Comment by eromano** [comment]
are you rinning ```yo alfresco-adf-app``` to generate your app ?

**Comment by nthphuong** [comment]
Yes, I already ran it in step 4.  
yo alfresco-adf-app
vi proxy.conf.js (Update domain of ACS)

**Comment by DenysVuika** [comment]
Please refer to the updated README here: https://github.com/Alfresco/generator-alfresco-adf-app#readme
It includes the details on how to setup node for Ubuntu, and was tested with 20 and 21.
