### ISSUE TITLE
File preview crashes app after viewing

### ISSUE THREAD

**Issue by uclaeamsavino** [Alfresco/generator-alfresco-adf-app#254]
Steps to reproduce:

1. Create an Attach File component in APS (ours lives in a tab structure)
![image](https://user-images.githubusercontent.com/43759901/80645240-b267fc80-8a1f-11ea-9ccc-b63fdf7564b9.png)
2. Upload a PDF document or any other file
3. Click Show from the context dropdown to the right to preview the file
![image](https://user-images.githubusercontent.com/43759901/80644796-18a04f80-8a1f-11ea-8b08-dcb5a9c7f435.png)
4. File Preview should work
5. Close preview

After closing preview, the entire app becomes unresponsive. Nothing can be clicked. Only a page refresh makes the page responsive again. There are no errors in the console. This is with the out of the box app just generated from yo.

I also tried this in a process with only one component - Attach File - just in case it was some weird combination of stuff we put in our full process. Same results.

UPDATE: I don't know how to fix this yet. But I know what's causing it. The adf-viewer and its overlay are hanging around and blocking all clicks. Even though the visibility goes away and you can see the page as normal, the overlay is still there. I deleted it in web inspector and now I can click other elements.

This seems to be the same problem:
https://hub.alfresco.com/t5/application-development/task-form-files-overlay-problem/td-p/295371

**Comment by fcorti** [comment]
https://issues.alfresco.com/jira/browse/ADF-5084

**Comment by trodix** [comment]
You can do a hack like I did by doing this :

```html
  <adf-viewer
    [overlayMode]="true"
    [nodeId]="nodeId"
    (showViewerChange)="onViewerGoBack()"
  >
...
</adf-viewer>
```

```ts
  onViewerGoBack() {
    const cleanUrl = this.router.url.split(new RegExp(/\([\S]+\)/, 'i'))[0];
    this.router.navigateByUrl(cleanUrl, {replaceUrl: true});
  }
```

**Comment by DenysVuika** [comment]
closing as this is not related to the yeoman generator
