### ISSUE TITLE
Cannot find name NodesApiService

### ISSUE THREAD

**Issue by unibravoc** [Alfresco/generator-alfresco-adf-app#286]
MacBook-Air:**adf-cli-activiti-cloud-acs-template** alf$ **npm run build --prod**

> adf-cli-activiti-cloud-acs-template@4.2.0 build /Users/alf/generator-alfresco-adf-app/app/templates/adf-cli-activiti-cloud-acs-template
> ng build

ERROR in src/app/file-view/file-view.component.ts:36:29 - **error TS2304: Cannot find name 'NodesApiService'.**

36     private nodeApiService: NodesApiService

**Comment by unibravoc** [comment]
My solution:

Edit file-view.component.ts
Add this line:
**import { NodesApiService } from '@alfresco/adf-core';**

**Comment by DenysVuika** [comment]
fixed and will be available with the next release
