### ISSUE TITLE
Yeoman generator unable to resolve dependencies

### ISSUE THREAD

**Issue by kerry-chin** [Alfresco/generator-alfresco-adf-app#310]
**Description:**
Attempting to follow the installation steps to create an ADF application, found at this page: https://www.alfresco.com/abn/adf/docs/tutorials/creating-your-first-adf-application/

**Observed behavior:**
Running the "yo alfresco-adf-app" command results in the following dependency errors:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: adf-cli-acs-template@4.0.0
npm ERR! Found: @angular/cdk@10.0.2
npm ERR! node_modules/@angular/cdk
npm ERR!   @angular/cdk@"10.0.2" from the root project
npm ERR!   peer @angular/cdk@">=10.0.1" from @alfresco/adf-content-services@4.0.0
npm ERR!   node_modules/@alfresco/adf-content-services
npm ERR!     @alfresco/adf-content-services@"4.0.0" from the root project
npm ERR!   2 more (@alfresco/adf-core, @angular/flex-layout)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cdk@"10.1.0" from @angular/material@10.1.0
npm ERR! node_modules/@angular/material
npm ERR!   @angular/material@"10.1.0" from the root project
npm ERR!   peer @angular/material@">=10.0.1" from @alfresco/adf-content-services@4.0.0
npm ERR!   node_modules/@alfresco/adf-content-services
npm ERR!     @alfresco/adf-content-services@"4.0.0" from the root project
npm ERR!   1 more (@alfresco/adf-core)
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\kchin\AppData\Local\npm-cache\eresolve-report.txt for a full report.
```

Tried both the --force and --legacy-peer-deps flags, as suggested, but still saw the same errors after each attempt.

**Expected behavior:**
The app should be generated without errors.

**Steps to reproduce:**
1.  Follow the installation steps outlined at https://www.alfresco.com/abn/adf/docs/tutorials/creating-your-first-adf-application/.
2. Run the "yo alfresco-adf-app" command.

**Environment:**
Angular CLI: 12.0.0
Node: 14.17.0
Package Manager: npm 7.13.0
OS: win32 x64

**Additional notes:**
The above dependency errors came _after correcting vulnerability issues_ produced when installing the generator:
1. After installing the generator via the "npm install -g generator-alfresco-adf-app@latest" command, received notification of 4 vulnerability issues.
2. Ran the suggested "npm audit fix" to correct the issues.

However, if I do NOT run "npm audit fix", I do not get dependency errors.  Instead, running "yo alfresco-adf-app" produces a different error:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @alfresco/adf-content-services@4.4.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by DenysVuika** [comment]
Please use 6.x version of the NPM, the 7.x has a known issues related to Angular projects

**Comment by kerry-chin** [comment]
Thank you @DenysVuika for the suggestion!  I downgraded to npm 6.14.13, and re-installed the generator and was able to run the "yo alfresco-adf-app" command.

Now it reports 85 vulnerabilities after building.  But curiously, running "npm audit" doesn't list anything:
```
found 85 vulnerabilities (4 low, 79 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

C:\Users\kchin\Documents\CGI\GNMA\Code\gnma-dams-alfresco>npm audit

                       === npm audit security report ===

found 0 vulnerabilities
 in 0 scanned packages
```

Should I run the "npm audit fix", or just ignore it and continue with the next steps in setting up my app?

**Comment by DenysVuika** [comment]
That happens all the time and those warnings come and go. We keep track all the time and upgrade/fix during release, but very often some appear later. For your case, maybe you need to "cd" into the project folder before running "npm audit"

**Comment by kerry-chin** [comment]
Duh, of course.  I see the list now, but left it alone.  I started the app without a problem, so for the time being, I will not fix anything.  I am merely exploring for the moment, and seeing where and how UI components can be re-styled (for branding purposes).  

Do you foresee any issues if I don't fix the vulnerabilities?  I am relatively new at this, so am worried about breaking things.

**Comment by DenysVuika** [comment]
For experimental and development purposes you can disregard warnings.

**Comment by DenysVuika** [comment]
Closing as the next release works fine with the NPM 7.x (tested with 7.18.1)

**Comment by tuchang** [comment]
> Closing as the next release works fine with the NPM 7.x (tested with 7.18.1)

Do you know what is the last compatible npm version?
