### ISSUE TITLE
Material icons outdated (4.10.1)

### ISSUE THREAD

**Issue by romainbrochot** [Alfresco/generator-alfresco-adf-app#360]
Hi,

The embedded Material Icons fonts in 4.10.1 are from 2016 (material icons 3.0.1) and then multiple icons are not displayed in ADF, for example "download".
It looks like the binaries managed by Google are quiet a mess
EDIT : https://github.com/google/material-design-icons/issues/1129

Regards,
Romain Brochot

**Comment by DenysVuika** [comment]
please raise the issue for ADF repositories, as generator does not maintain the material icons on its own
